package com.ravox.models.core.resourcepack;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import org.bukkit.Bukkit;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Locale;
import java.util.concurrent.Executors;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public final class ResourcePackService {
    private final JavaPlugin plugin;
    private final File packDir;
    private final boolean enabled;
    private final boolean force;
    private final String externalUrl;
    private final boolean hostEnabled;
    private final String hostPublic;
    private final int hostPort;
    private final String hostPath;
    private HttpServer httpServer;
    private File activeZip;
    private byte[] activeSha1;
    private String activeUrl;

    public ResourcePackService(JavaPlugin plugin) {
        this.plugin = plugin;
        FileConfiguration cfg = plugin.getConfig();
        this.enabled = cfg.getBoolean("resourcepack.enabled", true);
        this.force = cfg.getBoolean("resourcepack.force", true);
        this.externalUrl = cfg.getString("resourcepack.hosted_url", "").trim();
        this.hostEnabled = cfg.getBoolean("resourcepack.host.enabled", true);
        this.hostPublic = cfg.getString("resourcepack.host.public_host", "127.0.0.1");
        this.hostPort = cfg.getInt("resourcepack.host.port", 8777);
        this.hostPath = normalizePath(cfg.getString("resourcepack.host.path", "/ravoxmodels/pack.zip"));
        this.packDir = new File(plugin.getDataFolder(), "resourcepack");
        if (!packDir.exists()) {
            packDir.mkdirs();
        }
    }

    public void start() {
        if (!enabled) {
            return;
        }
        if (!externalUrl.isEmpty()) {
            activeUrl = externalUrl;
            return;
        }
        if (!hostEnabled) {
            return;
        }
        try {
            httpServer = HttpServer.create(new InetSocketAddress(hostPort), 0);
            httpServer.createContext(hostPath, new PackHandler());
            httpServer.setExecutor(Executors.newFixedThreadPool(2));
            httpServer.start();
            activeUrl = "http://" + hostPublic + ":" + hostPort + hostPath;
            plugin.getLogger().info("Resourcepack host started at " + activeUrl);
        } catch (IOException ex) {
            plugin.getLogger().warning("Could not start resourcepack host: " + ex.getMessage());
        }
    }

    public void stop() {
        if (httpServer != null) {
            httpServer.stop(0);
            httpServer = null;
        }
    }

    public boolean buildPack() {
        if (!enabled) {
            return false;
        }
        File zip = new File(packDir, "ravoxmodels-pack.zip");
        File temp = new File(packDir, "ravoxmodels-pack.tmp.zip");
        try (ZipOutputStream zos = new ZipOutputStream(Files.newOutputStream(temp.toPath()))) {
            addTextEntry(zos, "pack.mcmeta",
                    "{\n" +
                            "  \"pack\": {\n" +
                            "    \"pack_format\": 22,\n" +
                            "    \"description\": \"RavoxModels generated pack\"\n" +
                            "  }\n" +
                            "}\n");
            addTextEntry(zos, "assets/ravoxmodels/generated/marker.txt",
                    "Generated by RavoxModels " + plugin.getDescription().getVersion() + "\n");
        } catch (IOException ex) {
            plugin.getLogger().warning("Could not build resourcepack zip: " + ex.getMessage());
            return false;
        }
        try {
            Files.move(temp.toPath(), zip.toPath(), StandardCopyOption.REPLACE_EXISTING);
            activeZip = zip;
            activeSha1 = sha1(zip);
            if (!externalUrl.isEmpty()) {
                activeUrl = externalUrl;
            } else if (activeUrl == null && hostEnabled) {
                activeUrl = "http://" + hostPublic + ":" + hostPort + hostPath;
            }
            return true;
        } catch (IOException ex) {
            plugin.getLogger().warning("Could not finalize resourcepack zip: " + ex.getMessage());
            return false;
        }
    }

    public boolean applyToPlayer(Player player) {
        if (!enabled || activeUrl == null || activeSha1 == null) {
            return false;
        }
        player.setResourcePack(activeUrl, activeSha1);
        return true;
    }

    public int applyToAll() {
        int count = 0;
        for (Player player : Bukkit.getOnlinePlayers()) {
            if (applyToPlayer(player)) {
                count++;
            }
        }
        return count;
    }

    public boolean isForce() {
        return force;
    }

    public String getActiveUrl() {
        return activeUrl;
    }

    public String getActiveSha1Hex() {
        if (activeSha1 == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        for (byte b : activeSha1) {
            sb.append(String.format(Locale.ROOT, "%02x", b));
        }
        return sb.toString();
    }

    private static void addTextEntry(ZipOutputStream zos, String path, String content) throws IOException {
        ZipEntry entry = new ZipEntry(path);
        zos.putNextEntry(entry);
        byte[] bytes = content.getBytes();
        zos.write(bytes);
        zos.closeEntry();
    }

    private static byte[] sha1(File file) throws IOException {
        MessageDigest digest;
        try {
            digest = MessageDigest.getInstance("SHA-1");
        } catch (NoSuchAlgorithmException ex) {
            throw new IOException("SHA-1 unavailable", ex);
        }
        try (InputStream in = Files.newInputStream(file.toPath())) {
            byte[] buffer = new byte[8192];
            int read;
            while ((read = in.read(buffer)) != -1) {
                digest.update(buffer, 0, read);
            }
        }
        return digest.digest();
    }

    private static String normalizePath(String path) {
        if (path == null || path.isEmpty()) {
            return "/ravoxmodels/pack.zip";
        }
        return path.startsWith("/") ? path : "/" + path;
    }

    private final class PackHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            if (activeZip == null || !activeZip.exists()) {
                exchange.sendResponseHeaders(404, 0);
                exchange.close();
                return;
            }
            exchange.getResponseHeaders().add("Content-Type", "application/zip");
            exchange.sendResponseHeaders(200, activeZip.length());
            try (OutputStream out = exchange.getResponseBody()) {
                Files.copy(activeZip.toPath(), out);
            }
        }
    }
}
