<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ravox</groupId>
    <artifactId>ravoxmodels-parent</artifactId>
    <version>26.1</version>
    <packaging>pom</packaging>

    <name>ravoxmodels-parent</name>

    <modules>
        <module>ravoxmodels-api</module>
        <module>ravoxmodels-core</module>
        <module>ravoxmodels-bridge-customore</module>
    </modules>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <paper.api.version>26.1.2.build.43-alpha</paper.api.version>
    </properties>

    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
    </repositories>
</project>
