<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.ravox</groupId>
        <artifactId>ravoxmodels-parent</artifactId>
        <version>26.1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ravoxmodels-bridge-customore</artifactId>
    <name>ravoxmodels-bridge-customore</name>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.ravox</groupId>
            <artifactId>ravoxmodels-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>${paper.api.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>
